name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  riverpod_annotation: ^2.2.1
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
